/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WeatherforecastRequestBuilder, WeatherforecastRequestBuilderRequestsMetadata } from './weatherforecast/index.ts';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link WeatherClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
export function createWeatherClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(FormSerializationWriterFactory);
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultSerializer(TextSerializationWriterFactory);
    registerDefaultSerializer(MultipartSerializationWriterFactory);
    registerDefaultDeserializer(FormParseNodeFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    registerDefaultDeserializer(TextParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://app-tkela7hih6dji-node-reference.azurewebsites.net";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<WeatherClient>(requestAdapter, pathParameters, WeatherClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface WeatherClient extends BaseRequestBuilder<WeatherClient> {
    /**
     * The weatherforecast property
     */
    get weatherforecast(): WeatherforecastRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WeatherClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WeatherClientNavigationMetadata: Record<Exclude<keyof WeatherClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    weatherforecast: {
        requestsMetadata: WeatherforecastRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
