// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace WebApp.ApiClients.Models {
    /// <summary>pet status in the store</summary>
    public enum Pet_status
    {
        [EnumMember(Value = "available")]
        Available,
        [EnumMember(Value = "pending")]
        Pending,
        [EnumMember(Value = "sold")]
        Sold,
    }
}
