// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace WebApp.ApiClients.Pet.FindByStatus {
    public enum GetStatusQueryParameterType
    {
        [EnumMember(Value = "available")]
        Available,
        [EnumMember(Value = "pending")]
        Pending,
        [EnumMember(Value = "sold")]
        Sold,
    }
}
