name: Set Custom Metadata

on:
  workflow_dispatch:
    inputs:
      resource-id:
        description: 'The resource ID of the API Center'
        required: false
        default: ''
      resource-group:
        description: 'The resource group name of the API Center'
        required: false
        default: ''
      service-name:
        description: 'The service name of the API Center'
        required: false
        default: ''
      api-id:
        description: 'The API ID registered in the API Center'
        required: false
        default: ''
      metadata-key:
        description: 'The key of the metadata to set'
        required: true
      metadata-value:
        description: 'The value of the metadata to set'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  api-metadata:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install APIC extension
        shell: bash
        run: |
          az extension add --name apic-extension --allow-preview true --yes

      - name: Login to Azure
        uses: Azure/login@v3
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}

      - name: Set Custom Metadata
        shell: bash
        env:
          RESOURCE_ID: ${{ inputs['resource-id'] }}
          RESOURCE_GROUP: ${{ inputs['resource-group'] }}
          SERVICE_NAME: ${{ inputs['service-name'] }}
          API_ID: ${{ inputs['api-id'] }}
          METADATA_KEY: ${{ inputs['metadata-key'] }}
          METADATA_VALUE: ${{ inputs['metadata-value'] }}
        run: |
          ./infra/scripts/set-apimetadata.sh \
            --resource-id "$RESOURCE_ID" \
            --resource-group "$RESOURCE_GROUP" \
            --service-name "$SERVICE_NAME" \
            --api-id "$API_ID" \
            --metadata-key "$METADATA_KEY" \
            --metadata-value "$METADATA_VALUE"
